import logging
from dataclasses import dataclass
from decimal import Decimal
from typing import Any, Optional
from src.core.enums import OrderType

logger = logging.getLogger("trading_system")


@dataclass(frozen=True)
class Signal:
    """
    Immutable dataclass representing a trading signal generated by the strategy.
    """
    type: OrderType
    candle_close: Decimal
    confidence: Decimal  # Confidence percentage (e.g., 87.50)
    raw_vote: int        # Raw model vote (e.g., +6 or -5)

    @classmethod
    def from_lorentzian(
        cls,
        prediction_result: Any,
        candle_close: float | Decimal | str,
        neighbors_count: int = 8
    ) -> Optional["Signal"]:
        """
        Creates a Signal from Lorentzian strategy prediction results.
        """
        lorentz_name = prediction_result.signal.name

        if lorentz_name == "HOLD":
            return None

        if lorentz_name == "LONG":
            order_type = OrderType.LONG
        elif lorentz_name == "SHORT":
            order_type = OrderType.SHORT
        else:
            return None

        raw_vote = int(prediction_result.prediction)
        
        # Calculate confidence using Decimals
        raw_vote_dec = Decimal(str(abs(raw_vote)))
        neighbors_dec = Decimal(str(neighbors_count))
        confidence = (raw_vote_dec / neighbors_dec) * Decimal("100.0")
        confidence = confidence.quantize(Decimal("0.01"))

        close_dec = Decimal(str(candle_close))

        logger.info(
            f"{order_type.name} signal successfully generated | "
            f"Close: {close_dec:.2f} | Vote: {raw_vote:+} | Conf: {confidence}%"
        )

        return cls(
            type=order_type,
            candle_close=close_dec,
            confidence=confidence,
            raw_vote=raw_vote
        )